### ISSUE TITLE
Why does this need to burn gas to just register?

### ISSUE THREAD

**Issue by chrishobcroft** [luzzif/rails#3]
# Summary

I don't understand why I need to burn some gas just to register? e.g. just to be able to check my balance?

The UI explains something about "Tying your onchain Ethereum address to the Loopring Pay L2 system" - but I don't understand what that practically means in terms of needing to write to Ethereum.

Like, I can understand that depositing assets require some gas to be burned... but simply registering, and being able to check my balance. e.g. the use case where I don't deposit, but I receive a transfer from another address...

# Observed Behaviour

1: Load https://goerli-loopring-pay-ui.netlify.app/
![image](https://user-images.githubusercontent.com/2212651/86511746-9c105f80-be19-11ea-97b1-df68f35c04fe.png)

2: Click "Register"
![image](https://user-images.githubusercontent.com/2212651/86511765-c4985980-be19-11ea-960c-a4959b08d77c.png)

3. Select "MetaMask"
![image](https://user-images.githubusercontent.com/2212651/86511775-da0d8380-be19-11ea-8e81-9d4fe6e50ec0.png)

4. Click "Continue"
![image](https://user-images.githubusercontent.com/2212651/86511782-e4c81880-be19-11ea-8e30-e614b91c735c.png)

5. Click "Sign" (in MetaMask)
![image](https://user-images.githubusercontent.com/2212651/86511794-fc070600-be19-11ea-8280-c1f8d7205c93.png)

**Unexpected Behaviour: I have to pay gas just to register? Not even to deposit, but just to register? Huh? Why like this?**

# Expected Behaviour

I expect that in order to check my balance (e.g. to see if I have received a transfer from another address...) then I wouldn't need to first spend some money for gas (which I might not actually have!).

**Comment by luzzif** [comment]
I think this would be a great question to ask to the Loopring team directly, if you want a 110% accurate explanation, but I'll try to explain.
The Loopring L2 system doesn't work directly with native ETH accounts, but instead creates L2-specific accounts which are then used by the relayers to do their work (combining various transactions/trades in blocks and generating succint computation-correctness proofs that can be efficiently submitted on-chain). The registration consists in generating the L2-specific account, mapping it to your on-chain ETH account. Since this step is done on-chain, and involves a smart contract interaction, some gas has to be paid. 
Generally speaking, you'll spend gas in those processes that require interacting with the Ethereum blockchain (typically registering, depositing and withdrawing), but once inside the L2 system, you're free from it, so you can then transfer or trade at light-speed with little to no expenses.
Hope it was clear.
